//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoBrowserChooser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LaunchAlternateForIntranet {
            get {
                return ((bool)(this["LaunchAlternateForIntranet"]));
            }
            set {
                this["LaunchAlternateForIntranet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("microsoft.com;osdinfra.net")]
        public string LaunchAlternateForDomains {
            get {
                return ((string)(this["LaunchAlternateForDomains"]));
            }
            set {
                this["LaunchAlternateForDomains"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LaunchAlternateForClickOnce {
            get {
                return ((bool)(this["LaunchAlternateForClickOnce"]));
            }
            set {
                this["LaunchAlternateForClickOnce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{LocalApplicationData}\\Google\\Chrome\\Application\\chrome.exe")]
        public string MainBrowser {
            get {
                return ((string)(this["MainBrowser"]));
            }
            set {
                this["MainBrowser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iexplore.exe")]
        public string AlternateBrowser {
            get {
                return ((string)(this["AlternateBrowser"]));
            }
            set {
                this["AlternateBrowser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LaunchAlternateForLocalhost {
            get {
                return ((bool)(this["LaunchAlternateForLocalhost"]));
            }
            set {
                this["LaunchAlternateForLocalhost"] = value;
            }
        }
    }
}
